services:
  spring-boot:
    build:
      context: ./Backend/booking-application
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    container_name: backend-booking-app

  react-app:
    build:
      context: ./Frontend/booking-application
    ports:
      - "3000:80"
    container_name: frontend-booking-ui
    depends_on:
      - spring-boot
