server:
    port: 8082
    servlet:
        context-path: /backend
spring:
    application:
        name: booking-management-system
    datasource:
        url: jdbc:h2:mem:booking
        username: ${H2_USER}
        password: ${H2_PWD}
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

jwt:
  excluded-paths: /user/login,/user/register,/h2-console/**,/actuator/**,/**/*.jpg,/payment/type,/rooms/filters
  access_token:
    expire: ${JWT_ACCESS_EXPIRE_TIME:30} # in minutes
  refresh_token:
    expire: ${JWT_REFRESH_EXPIRE_TIME:24} # in hours
  public:
    key: ${JWT_PUBLIC_KEY}
  private:
    key: ${JWT_PRIVATE_KEY}

